online_store/online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include(('shop.urls', 'online_store'), namespace='shop')),
    path('users/', include(('users.urls', 'online_store'), namespace='users'))
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)
urlpatterns += staticfiles_urlpatterns()

online_store/shop/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('products/', views.products_list, name='products_list'),
    path('cart/', views.cart, name='cart'),
    path('delete_cart_item/<int:pk>', views.delete_cart_item, name='delete_cart_item'),
    path('edit_cart_items/<int:pk>', views.edit_cart_items, name='edit_cart_items'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('create_order', views.create_order, name='create_order'),
    path('rate_product/<int:pk>', views.rate_product, name='rate_product'),
    path('orders/', views.orders, name='orders'),
]

online_store/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('sign_in/', views.sign_in, name='sign_in'),
    path('sign_out/', views.sign_out, name='sign_out'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('my_profile/', views.my_profile, name='my_profile')
]

online_store/users/models.py
from django.db import models

online_store/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth.models import User
from .bulma_mixin import BulmaMixin


class SignUpForm(BulmaMixin, UserCreationForm):
    first_name = forms.CharField(label='Введите ваше имя')
    last_name = forms.CharField(label='Введите вашу фамилию')
    username = forms.CharField(label='Придумайте ник')
    email = forms.EmailField(label='Введите ваш email')
    password1 = forms.CharField(widget=forms.PasswordInput(), label='Придумайте пароль')
    password2 = forms.CharField(widget=forms.PasswordInput(), label='Повторите пароль')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class SignInForm(BulmaMixin, AuthenticationForm):
    username = forms.CharField(label='Введите ник')
    password = forms.CharField(widget=forms.PasswordInput(), label='Введите пароль')

    class Meta:
        model = User
        fields = ['username', 'password']


class EditProfileForm(BulmaMixin, forms.ModelForm):
    last_name = forms.CharField(label='Изменить фамилию')
    first_name = forms.CharField(label='Изменить имя')
    username = forms.CharField(label='Изменить ник')
    email = forms.EmailField(label='Изменить email')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']


class ResetPasswordForm(BulmaMixin, PasswordChangeForm):
    old_password = forms.PasswordInput()
    new_password1 = forms.PasswordInput()
    new_password2 = forms.PasswordInput()

    class Meta:
        model = User
        fields = ['old_password', 'new_password1', 'new_password2']

online_store/users/views.py
from django.shortcuts import render, redirect
from . import forms
from django.contrib.auth import login, logout, update_session_auth_hash


def sign_up(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:sign_in')
    form = forms.SignUpForm()
    return render(request, 'sign_up.html', {'form': form})


def sign_in(request):
    if request.method == 'POST':
        form = forms.SignInForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('shop:products_list')
    form = forms.SignInForm()
    return render(request, 'sign_in.html', {'form': form})


def sign_out(request):
    logout(request)
    return redirect('users:sign_in')


def edit_profile(request):
    form = forms.EditProfileForm(request.POST, instance=request.user)
    if form.is_valid():
        form.save()
        return redirect('shop:products_list')
    form = forms.EditProfileForm(instance=request.user)
    return render(request, 'edit_profile.html', {'form': form})


def reset_password(request):
    form = forms.ResetPasswordForm(request.user, request.POST)

    if request.method == 'POST' and form.is_valid():
        user = form.save()
        update_session_auth_hash(request, user)
        return redirect('users:sign_in')
    form = forms.ResetPasswordForm(request.user)
    return render(request, 'reset_password.html', {'form': form})


def my_profile(request):
    user = request.GET.get('user')
    return render(request, 'my_profile.html')

online_store/users/templates/edit_profile.html
{% extends 'base_layout.html' %}


{% block auth %}
    <div class="columns is-centered">
         <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form" method="post" enctype="multipart/form-data">
                    <h1 class="title has-text-centered is-2">
                        Edit Profile
                    </h1>
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="field">
                                <label for="{{ field.id_for_label }}" class="label">
                                    {{ field.label }}
                                </label>
                                <div class="control">
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                    <button class="button is-primary is-fullwidth" type="submit">
                        Submit
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

online_store/users/templates/my_profile.html
{% extends 'base_layout.html' %}


{% block content %}
    <div class="title is-2 has-text-black has-text-centered">Здравствуй, {{ user.first_name }}</div>
    <section class="section">
        <div class="columns">
            <div class="column is-3">
                <div class="columns is-gapless">
                    <div class="column is-2">
                        <a href="{% url 'users:my_profile' %}">
                            <ion-icon class="icon my-1" name="person-outline"></ion-icon>
                    </div>
                    <div class="column is-9">
                        <div class="subtitle is-6">{{ user.first_name }} {{ user.last_name }}
                            {% if user.is_superuser %}
                            <ion-icon name="star-outline"></ion-icon>
                            {% endif %}
                            <br> {{ user.email }}
                        </div>
                        </a>
                    </div>
                </div>
                <hr>
                <div class="columns my-4">
                   <div class="column is-2">
                        <a href="{% url 'shop:cart' %}">
                        <ion-icon class="icon " name="cart-outline"></ion-icon>
                   </div>
                    <div class="column ">
                        <div class="subtitle is-6">Корзина</div>
                    </div>
                    <div class="column">
                        <div class="subtitle is-6">{{ item.quantity }}</div>
                    </div>
                    </a>
                </div>
                <div class="columns my-4">
                    <div class="column is-2">
                        <a href="{% url 'users:sign_out' %}">
                            <ion-icon class="icon" name="log-out-outline"></ion-icon>
                    </div>
                    <div class="column">
                        <div class="subtitle is-6">
                            Выход
                        </div>
                        </a>
                    </div>
                </div>
            </div>
            <div class="column is-9">
                <div class="box" style="border-radius: 15px;">
                    <div class="columns">
                        <div class="column is-9"><div class="title is-4">О пользователе</div></div>
                        <div class="column">
                            <a class="button is-success" href="{% url 'users:edit_profile' %}">
                                <ion-icon class="icon mr-2" name="create-outline"></ion-icon>
                                Изменить профиль
                            </a>
                        </div>
                    </div>
                    <hr>
                    <div class="columns">
                        <div class="column">
                            <div class="subtitle is-5">Имя</div>
                        </div>
                        <div class="column">
                            <div class="subtitle is-6">
                                {{ user.first_name }}
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column">
                            <div class="subtitle is-5">
                                Фамилия
                            </div>
                        </div>
                        <div class="column">
                            <div class="subtitle is-6">
                                {{ user.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column">
                            <div class="subtitle is-5">
                                Email адресс
                            </div>
                        </div>
                        <div class="column">
                            <div class="subtitle is-6">
                                {{ user.email }}
                            </div>
                        </div>
                    </div>
                    <div class="columns">
                        <div class="column">
                            <div class="subtitle is-5">
                                Пароль
                            </div>
                        </div>
                        <div class="column">
                            <div class="subtitle is-6"">
                            <a href="{% url 'users:reset_password' %}">Забыли пароль?</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

online_store/users/templates/reset_password.html
{% extends 'base_layout.html' %}

{% block auth %}
    <div class="columns is-centered">
        <div class="column is-4">
            <div class="box has-background-info-light">
                <form class="form" method="POST" enctype="multipart/form-data">
                    <div class="title has-text-centered is-2">
                        Reset Password
                    </div>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label for="{{ field.id_for_label }}" class="label">
                                {{ field.label }}
                            </label>
                        {{ field }}
                        </div>
                    {% endfor %}
                <button class="button is-primary is-fullwidth" type="submit">
                    Submit
                </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

online_store/users/templates/sign_in.html
{% extends 'base_layout.html' %}

{% block auth %}
    <body class="section bs">
    <div class="columns is-centered">
        <div class="column is-5">
            <div class="box back" style="border-radius:15px; min-height:500px;">
                <div class="title is-2 has-text-centered">Вход</div>
                <hr>
                <form class="form " method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field ">
                            <label class="label" for="{{ field.id_for_label }}">
                                {{ field.label }}
                            </label>
                            <div class="control"    >
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-info is-fullwidth">
                        Войти
                    </button>
                    <div class="columns my-2">
                        <div class="column ">
                            <label class="checkbox">
                                <input type="checkbox">
                                Запомнить меня
                            </label>
                        </div>
                        <div class="column ">
                            <a href="{% url 'users:sign_up' %}">
                                Зарегестрироваться
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </body>
{% endblock %}

online_store/users/templates/sign_up.html
{% extends 'base_layout.html' %}
{% load static %}

{% block auth %}
    <body class="section bs">
    <div class="columns is-centered">
        <div class="column is-5">
            <div class="box back " style="border-radius:35px">
                <div class="title is-2 has-text-centered">Регистрация</div>
                <hr>
                <form class="form" method="post" >
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="field">
                            <label class="label" for="{{ field.id_for_label }}">
                                {{ field.label }}
                            </label>
                            <div class="control" >
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}
                    <button type="submit" class="button is-info is-fullwidth">
                        Продолжить
                    </button>
                     <div class="columns">
                         <div class="column     ">
                             <label class="checkbox">
                              <input type="checkbox">
                              Я согласен с <a href="https://tilda.cc/ru/privacy-generator/">политикой сайта</a>
                            </label>
                         </div>
                         <div class="column">
                             <a class="subtitle is-6" href="{% url 'users:sign_in' %}">Уже есть аккаунт ? <b>Войдите</b></a>
                         </div>
                     </div>
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}